services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  app:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: spring-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: deploy
      AWS_DB_URL: ${RDS_DB_URL}
      AWS_DB_USERNAME: ${RDS_DB_USERNAME}
      AWS_DB_PASSWORD: ${RDS_DB_PASSWORD}
      AWS_REDIS_URL: redis
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
    networks:
      - app-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
